dailyfresh/dailyfresh/urls.py
# coding:utf-8
"""dailyfresh URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls')),    # 用户管理功能部分
    url(r'^index/',include('df_goods.urls')),   # 商品展示功能部分
    url(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    url(r'^carts/', include('df_cars.urls')),   # 购物车功能部分
    url(r'^order/', include('df_order.urls')),  # 订单功能部分
    # url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cars/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
    url(r'^$', views.carts),
    url(r'^(\d+)_(\d+)/$', views.add),
    url(r'^edit_(\d+)_(\d+)/$', views.edit),
    url(r'^delete_(\d+)/$', views.delete),
]

dailyfresh/df_user/urls.py
# coding:utf-8
from django.conf.urls import include, url
import views

urlpatterns = [
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url(r'^login_out/$', views.login_out),
    url(r'^login/login_check/$', views.login_check),
    url(r'^order_(\d+)/$', views.user_center_order),
    url(r'^register/uname_check/$', views.uname_check),
    url(r'^user_center_info/$', views.user_center_info),
    url(r'^register/register_handle/$', views.register_handle),
]

dailyfresh/df_order/models.py
from django.db import models


class OrderInfo(models.Model):
    """订单信息"""
    oid = models.CharField(max_length=20, primary_key=True)
    user=models.ForeignKey('df_user.UserInfo')
    odata = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6,decimal_places=2)
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    """订单详情"""
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey('OrderInfo')
    price = models.DecimalField(max_digits=5,decimal_places=2)
    count = models.IntegerField()

dailyfresh/df_user/models.py
from django.db import models


class UserInfo(models.Model):
    """用户信息"""
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    uyoubian = models.CharField(max_length=6, default='')
    yphone = models.CharField(max_length=11, default='')

dailyfresh/df_user/views.py
# coding=utf-8
from django.core.paginator import Paginator
from django.shortcuts import render,redirect;
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect;
from hashlib import sha1;
from models import UserInfo;
from datetime import *;
import user_decorator;
from df_goods.models import GoodsInfo;
from df_order.models import *;
from django.views.decorators.csrf import csrf_exempt;
'''
注册功能
1.用户名是否唯一
2.确认两次密码是否相同
3.密码加密存储

'''


def register(request):
    """注册页"""
    title = '天天生鲜-注册'
    return render(request, 'df_user/register.html',{'title':title})


def login(request):
    """登陆页"""
    title = '天天生鲜-登陆'
    return render(request, 'df_user/login.html',{'title':title})


def login_out(request):
    """退出登陆"""
    request.session.flush()
    response = HttpResponseRedirect('/index/')
    return response


def uname_check(request):
    """用户名验证"""
    # 获取用户输入uname
    check_uname = request.POST.get('check_uname')
    # 检验数据库中是否有相同uname
    check_result = UserInfo.objects.filter(uname=check_uname).exists()
    # 若数据库中存在则返回True
    return JsonResponse({'check':check_result})


def login_check(request):
    """登陆验证"""
    post = request.POST
    login_name = post.get("username")
    login_pwd = post.get("pwd")
    # 如果cookie中有‘url’则跳转到之前记录的url,否则跳转到主页
    response = HttpResponseRedirect(request.COOKIES.get('url','/index/'))
    response.delete_cookie('url')
    check_result = UserInfo.objects.filter(uname=login_name).exists()
    if check_result:
        # 对用户输入密码进行加密
        s1 = sha1()
        s1.update(login_pwd)
        login_pwd = s1.hexdigest()

        check_pwd = UserInfo.objects.filter(uname=login_name).values('upwd')[0]['upwd']
        login_id = UserInfo.objects.filter(uname=login_name)[0].id
        # 验证密码是否正确
        if check_pwd == login_pwd:
            post = request.POST
            jizhu = post.get('jizhu')
            if jizhu:
                # cookie未定义时间则关闭浏览器过期
                response.set_cookie('login_name',login_name,None,datetime(2018,1,1))
                print('已经记住密码')
            else:
                response.set_cookie('login_name', '', max_age=-1)
                print('未成功记录密码')

            print('登陆成功')
            # 存储session
            request.session['myname']=login_name
            request.session['id'] = login_id
            # request.session.flush()
            # 获取sessi
            # id = request.session.get('id')
            # 删除session
            # del request.session['myname'],request.session['id']
            return response
        else:
            print('密码错误')
            content = {'title':'用户登陆','error_name':0,'error_pwd':1}
            return render(request,'df_user/login.html',content)
    else:
        response.set_cookie('login_name', '', max_age=-1)
        content = {'title': '用户登陆', 'error_name': 1, 'error_pwd': 0}
        return render(request,'df_user/login.html',content)


def register_handle(request):
    """注册验证"""
    # 获取注册信息
    post = request.POST
    uname = post.get('user_name')
    upwd1 = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    # 验证两次密码是否相同
    if upwd1 == upwd2:
        # 密码加密
        s1 = sha1()
        s1.update(upwd1)
        upwd3 = s1.hexdigest()

        #存入数据库
        user = UserInfo()
        user.uname = uname
        user.upwd = upwd3
        user.uemail = uemail
        user.save()

        return redirect('/user/login/')

    else:
        return redirect('/user/register/')


@user_decorator.login
def user_center_info(request):
    """用户中心"""
    rec_bro = request.COOKIES.get('goods_ids', '')
    rec_good =[]
    rec_list = rec_bro.split(',')
    if rec_list !=['']:
        for good in rec_list:
            good_obj=GoodsInfo.objects.get(pk=int(good))
            rec_good.append(good_obj)
    return render(request, 'df_user/user_center_info.html',{'page_style':0,'rec_good':rec_good})


@user_decorator.login
def user_center_order(request,pindex):
    """用户中心订单页"""
    uid = request.session['id']
    user_order = OrderInfo.objects.filter(user_id=uid).order_by('-oid')
    print pindex
    print('uid:%s'%user_order)
    paginator = Paginator(user_order,'2')
    page = paginator.page(pindex)
    print('page:%s' % page)
    print('page.paginator:%s' % page.paginator)
    return render(request,'df_user/user_center_order.html',{
        'uid':user_order,
        'page':page,

    })

dailyfresh/templates/df_user/index.html
{% extends 'base_foot_top.html' %}
{% block head %}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock head%}
{% block body_frame%}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">草莓</a></h4>
					<a href="#"><img src="/static/images/goods/goods003.jpg"></a>
					<div class="prize">¥ 30.00</div>
				</li>
				<li>
					<h4><a href="#">葡萄</a></h4>
					<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
					<div class="prize">¥ 5.50</div>
				</li>
				<li>
					<h4><a href="#">柠檬</a></h4>
					<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
					<div class="prize">¥ 3.90</div>
				</li>
				<li>
					<h4><a href="#">奇异果</a></h4>
					<a href="#"><img src="/static/images/goods/goods012.jpg"></a>
					<div class="prize">¥ 25.80</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">河虾</a>
				<a href="#">扇贝</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">青岛野生海捕大青虾</a></h4>
					<a href="#"><img src="/static/images/goods/goods018.jpg"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">扇贝</a></h4>
					<a href="#"><img src="/static/images/goods/goods019.jpg"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">冷冻秋刀鱼</a></h4>
					<a href="#"><img src="/static/images/goods/goods020.jpg"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">基围虾</a></h4>
					<a href="#"><img src="/static/images/goods/goods021.jpg"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>
{% endblock body_frame%}

dailyfresh/templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}
<script>
	$(function () {
		$('#username').blur(function () {
			$('#username').next().hide()
        })
		$('#pwd').blur(function () {
			$('#pwd').next().hide()
        })
		$('#jizhu').click(function () {
		    if($('#jizhu').prop('checked')){
		        $.cookie('jizhu',true,{expires:7,path:'/'})
			}
			else{
		        $.cookie('jizhu',false,{expires:7,path:'/'})
			}
        })

		/*
		 问题:无论cookie为何值，checkbox状态均不改变 10/18/21
		 解决时间：10/19/9
		 cookie返回值中的true何false都是str类型的不能直接作为boolean参与判断
		 check移除操作使用.pror时发现无效果，可能与JQuery版本有关，换成attr和removeAttr
		 */
		if($.cookie('jizhu')=='true'){
		    $('#jizhu').attr('checked','checked');

			if($.cookie('login_name')){
			/*未完成功能：记住用户名
			* 	此处已经获取记住用户名信息
			* 1.input需要改写autocomplete已完成已用户名的呈现*/
			}
		}
		else{
		    $('#jizhu').removeAttr('checked');
		}

    })
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="../df_goods/index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">



					<form id="log_form" action="/user/login/login_check/" method="post" autocomplete="off"  >
						<input type="text" id="username" name="username" class="name_input" placeholder="请输入用户名"
							   value="{{login_name|default:''}}">
						<div class="user_error">输入错误</div>
						<input type="password" id="pwd" name="pwd" class="pass_input" placeholder="请输入密码" value="{{login_pwd|default:''}}" >
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input id="jizhu" type="checkbox" name="jizhu" checked="checked">
							<label >记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{%if error_name or error_pwd %}
					<script>
						$('#username').next().show()
						$('#pwd').next().show()
					</script>
					{%endif%}
{% endblock body %}


dailyfresh/templates/df_user/register.html
{% extends 'base_foot.html' %}

{% block head %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form id="reg_form" action="register_handle/" method="post" autocomplete="off">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

dailyfresh/templates/df_user/user_center_info.html
{% extends 'base_search.html' %}

{% block search_frame %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/index/user_center_info" class="active">· 个人信息</a></li>
				<li><a href="/user/user_center_order">· 全部订单</a></li>
				<li><a href="/user/user_center_site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>18210569700</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                            {% for good in rec_good %}
                            <li>
                                <a href="/index/{{ good.id }}/"><img src="/static/{{good.gpic}}"></a>
                                <h4><a href="/index/{{ good.id }}">{{good.gtitle}}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{good.gprice}}</span>
                                    <span class="unit">{{good.gprice}}/{{good.gunit}}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                            {% endfor %}

			        </ul>
		</div>
		</div>
	</div>
{% endblock search_frame %}

dailyfresh/templates/df_user/user_center_order.html
{% extends 'base_search.html' %}

{% block search_frame%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="user_center_info.html">· 个人信息</a></li>
				<li><a href="user_center_order.html" class="active">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for uid in page %}

				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ uid.odata }}</li>
					<li class="col02">订单号: {{ uid.oid }}</li>
					<li class="col02 stress">{% if uid.oIsPay == True %}
                                    已支付
                                {% else %}
                                    已支付
                                {% endif %}</li>
				</ul>


				<table class="order_list_table w980">
					<tbody>
						<tr>

							<td width="55%">
                                {% for order_detail in uid.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ order_detail.goods.gpic }}"></li>
									<li class="col02">{{ order_detail.goods.gtitle }}<em>{{ order_detail.goods.gprice }}元/{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}</li>
									<li class="col04">{{ order_detail.price }}元</li>
								</ul>
                                {% endfor %}
                            </td>

							<td width="15%">{{ uid.ototal }}元</td>
							<td width="15%">
                                {% if uid.oIsPay == True %}
                                    交易完成
                                {% else %}
                                    待付款
                                {% endif %}
                            </td>
							<td width="15%"><a id="{{ uid.oid }}" href="javascript:pay({{ uid.oid }});" class="oper_btn">
                                {% if uid.oIsPay == True %}
                                    交易详情
                                {% else %}
                                    去付款
                                {% endif %}</a></td>
						</tr>
					</tbody>
				</table>
                {% endfor %}



{#                分页#}

				<div class="pagenation">
				{%if page.has_previous%}
				<a href="/user/order_{{page.number|add:'-1'}}/">上一页</a>
				{%endif%}

				{%for pages in page.paginator.page_range%}

				<a href="/user/order_{{pages}}/"
				   {%if pages == page.number%}
				   class="active"
				   {%endif%}
				>{{pages}}</a>

				{%endfor%}

				{%if page.has_next%}
				<a href="/user/order_{{page.number|add:'1'}}/">下一页</a>
				{%endif%}

			</div>


		</div>
	</div>
    <script>
    function pay(oid) {

        var pay_but = $('#'+oid).text().trim()
        if(pay_but == "去付款"){
            $.post('/order/pay/',{'oid':oid},function (data) {
            if(data.err == '1'){
                alert('支付成功')
            }else{
                alert('支付失败,请重试')
            }
            window.location.reload();
        })
        }else{
            alert('详情功能未开发')
        }
    }
    </script>
{% endblock search_frame%}